#!/usr/bin/env python
#
#  Copyright (c) 2014-2018, Centre for Genomic Regulation (CRG).
#  Copyright (c) 2014-2018, Jose Espinosa-Carrasco and the respective authors.
#
#  This file is part of Pergola.
#
#  Pergola is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#
#  Pergola is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with Pergola.  If not, see <http://www.gnu.org/licenses/>.

version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.13

    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "setup.py" }}

      - run:
          name: install python dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install scipy
            sudo pip install twine
            sudo python setup.py install
            python pergola/test/test_all.py

      - save_cache:
          key: dependency-cache-{{ checksum "setup.py" }}
          paths:
            - "venv"

  deploy:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout

      - run:
          name: install python dependencies
          command: |
            sudo pip install -r requirements.txt
            sudo pip install scipy
            sudo pip install twine

      - run:
          name: init .pypirc
          command: |
            if git log -1 --decorate --all --oneline --graph | grep "[0-9]\+\.[0-9]\+\.[0-9]";
            then
              CIRCLE_TAG=$(git describe)
              python setup.py verify
              echo -e "[distutils]" >> ~/.pypirc
              echo -e "index-servers=" >> ~/.pypirc
              echo -e " testpypi" >> ~/.pypirc
              echo -e " pypi" >> ~/.pypirc
              echo -e "[pypi]" >> ~/.pypirc
              echo -e "repository: https://upload.pypi.org/legacy/" >> ~/.pypirc
              echo -e "username = JoseEspinosa" >> ~/.pypirc
              echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
              sudo python setup.py sdist
              sudo python setup.py bdist_wheel
              twine upload dist/*
            else
              echo "Not a release, skipping build"
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              ignore: /^testing-.*/
            branches:
              only:
                - master